#!/bin/sh

# Install packages with retry logic
set -e
set -u
export DEBIAN_FRONTEND=noninteractive

# Update package index
apt-get update -qq

# Install packages with retry logic
n=0
max=2
until [ $n -gt $max ]; do
  set +e
  (
    apt-get install -y --no-install-recommends "$@"
  )
  CODE=$?
  set -e
  if [ $CODE -eq 0 ]; then
    break
  fi
  if [ $n -eq $max ]; then
    exit $CODE
  fi
  echo "apt failed, retrying in 10 seconds..."
  sleep 10
  n=$(($n + 1))
done

# Clean up after installation
apt-get autoremove -y
rm -r /var/lib/apt/lists /var/cache/apt/archives
