name: Docker common actions
description: Common actions for docker
inputs:
  push:
    type: boolean
    default: false
    required: false
    description: Push images to docker hub
  platforms:
    type: string
    default: linux/amd64
    required: false
    description: Platforms to build for
  docker_hub_username:
    type: string
    default: ''
    required: false
    description: DockerHub username
  docker_hub_token:
    type: string
    default: ''
    required: false
    description: DockerHub token
  ghcr_token:
    type: string
    default: ''
    required: false
    description: GitHub Container Registry token
  python_base_image:
    type: string
    default: 3.8.18-slim-bookworm
    required: false
    description: Base image for python
  is_default_version:
    type: boolean
    default: false
    required: false
    description: Is this the default versions
  pi_version:
    type: string
    default: ''
    required: true
    description: Version of privacyidea
runs:
  using: "composite"
  steps:
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ inputs.docker_hub_username }}
        password: ${{ inputs.docker_hub_token }}
    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.ghcr_token }}
    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v5
      with:
        flavor: |
          latest=false
        images: |
          khalibre/privacyidea
          ghcr.io/Khalibre/privacyidea
        tags: |
          type=semver,pattern={{major}}.{{minor}}.{{patch}},enable=${{ github.event_name == 'push' && inputs.is_default_version && github.ref_type == 'tag' }}
          type=raw,value={{tag}}-python-${{ inputs.python_base_image }},enable=${{ github.event_name == 'push' && github.ref_type == 'tag' }}
          type=raw,value={{tag}},enable=${{ github.event_name == 'push' && inputs.is_default_version && github.ref_type == 'tag' }}
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=ref,event=pr,enable=${{ github.event_name == 'pull_request' }}
          type=sha,enable=${{ github.event_name == 'push' }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Load image for structure tests
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        load: true
        platforms: linux/amd64
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        build-args: |
          BASE_IMAGE_TAG=${{ inputs.python_base_image }}
          PI_VERSION=${{ inputs.pi_version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Container Structure Tests
      shell: bash
      run: |
        curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
        chmod +x container-structure-test-linux-amd64
        mkdir -p $HOME/.local/bin
        mv container-structure-test-linux-amd64 $HOME/.local/bin/container-structure-test
        container-structure-test test --image ${{ fromJSON(steps.docker_meta.outputs.json).tags[0] }} --config structure-tests.yaml -o text >> $GITHUB_STEP_SUMMARY
    - name: Build and push
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ inputs.push }}
        load: ${{ !inputs.push }}
        platforms: ${{ inputs.platforms }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        build-args: |
          BASE_IMAGE_TAG=${{ inputs.python_base_image }}
          PI_VERSION=${{ inputs.pi_version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
